# Generated by Django 5.1.6 on 2025-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0005_rename_ticket_id_ticket_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_pending_tickets', 'Can view pending tickets'), ('view_completed_tickets', 'Can view completed tickets'), ('view_escalated_tickets', 'Can view escalated tickets')]},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Escalated', 'Escalated'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
