# Generated by Django 5.1.6 on 2025-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0006_alter_ticket_options_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_pending_tickets', 'Can view pending tickets'), ('view_escalated_tickets', 'Can view escalated tickets')]},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Escalated', 'Escalated')], default='Pending', max_length=20),
        ),
    ]
