# Generated by Django 5.1.6 on 2025-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=100, unique=True)),
                ('ticket_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('priority_level', models.CharField(max_length=100)),
                ('preferred_contact_method', models.CharField(max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('date_created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
